spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.dungeon-hub.net/realms/dungeon-hub-test
spring.security.oauth2.resourceserver.jwt.public-key-location=https://auth.dungeon-hub.net/realms/dungeon-hub-test
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://auth.dungeon-hub.net/realms/dungeon-hub-test/protocol/openid-connect/certs

spring.datasource.url=jdbc:postgresql://localhost:5432/dungeon-hub
spring.datasource.username=root
spring.datasource.password=root