spring.config.import=file:${user.home}/dungeon-hub/config/server_config.properties

spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations/{vendor}
spring.flyway.default-schema=flyway

spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=true
spring.jackson.serialization.write-date-timestamps-as-nanoseconds=false
spring.mvc.converters.preferred-json-mapper=gson
springdoc.api-docs.path=/api-src

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://auth.dungeon-hub.net/realms/dungeon-hub
spring.security.oauth2.resourceserver.jwt.public-key-location=https://auth.dungeon-hub.net/realms/dungeon-hub
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://auth.dungeon-hub.net/realms/dungeon-hub/protocol/openid-connect/certs
