create table carry_difficulty_history
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    carry_difficulty BIGINT    NOT NULL REFERENCES carry_difficulty (id) on delete cascade,
    price            BIGINT    NOT NULL,
    bulk_price       BIGINT,
    bulk_amount      BIGINT,
    score            BIGINT    NOT NULL,
    date_from        TIMESTAMP WITH TIME ZONE NOT NULL,
    date_to          TIMESTAMP WITH TIME ZONE NOT NULL
);

create index idx_carry_difficulty_history_period
    on carry_difficulty_history (carry_difficulty, date_from, date_to);
